language: java
jdk:
  - oraclejdk7
after_success:
  - echo "<settings><servers><server><id>permutive-internal-repo</id><username>\${env.S3_LIBRARIES_KEY}</username><password>\${env.S3_LIBRARIES_SECRET}</password></server></servers></settings>" > ~/settings.xml
  - mvn deploy --settings ~/settings.xml